apiVersion: skaffold/v4beta12
kind: Config
build:
  artifacts:
    - image: omerkanli/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
  local:
    push: false
manifests:
  rawYaml:
    - infra/k8s/*.yaml

deploy:
  statusCheck: true